modLoader="javafml"
loaderVersion="[40,)"

license="All rights reserved"
issueTrackerURL="https://github.com/IamBlueSlime/SlimmyMods/issues"
logoFile="pack.png"

[[mods]]
modId="computerthings"
version="${file.jarVersion}"
displayName="ComputerThings"
displayURL="https://www.curseforge.com/minecraft/mc-mods/computer-things"
authors="IamBlueSlime"
description='''

'''

[[dependencies.computerthings]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"

[[dependencies.computerthings]]
modId="computercraft"
mandatory=false
versionRange="[1.100,)"
ordering="NONE"
side="BOTH"
