modLoader="javafml"
loaderVersion="[40,)"

license="All rights reserved"
issueTrackerURL="https://github.com/IamBlueSlime/SlimmyMods/issues"
logoFile="pack.png"

[[mods]]
modId="keepmykeys"
version="${file.jarVersion}"
displayName="KeepMyKeys"
displayURL="https://www.curseforge.com/minecraft/mc-mods/keep-my-keys"
authors="IamBlueSlime"
description='''
Import your controls from another Minecraft setup, ending the pain
to reconfigure your keys every time you test a new modpack.
'''

[[dependencies.keepmykeys]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
