modLoader="javafml"
loaderVersion="[40,)"

license="All rights reserved"
issueTrackerURL="https://github.com/IamBlueSlime/SlimmyMods/issues"
logoFile="pack.png"

[[mods]]
modId="ledmc"
version="${file.jarVersion}"
displayName="LedMC"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ledmc"
authors="IamBlueSlime"
description='''
Let Minecraft control your RGB peripherals!
'''

[[dependencies.ledmc]]
modId="forge"
mandatory=true
versionRange="[40,)"
ordering="NONE"
side="BOTH"
